"use client";

import { useEffect, useState } from "react";
import styles from "../c5.module.css";

async function call(url, method = "GET", body) { const response = await fetch(url, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined, cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "The record could not be loaded."); return result; }

export default function CorrectionsDevelopment() {
  const [contributors, setContributors] = useState([]); const [id, setId] = useState(""); const [profile, setProfile] = useState(null); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [newModule, setNewModule] = useState("");
  useEffect(() => { call("/api/corrections/contributors").then((result) => { setContributors(result.contributors); setId(result.contributors[0]?.id || ""); }).catch((error) => setNotice(error.message)); }, []);
  useEffect(() => { if (id) call(`/api/corrections/contributors/${id}/development`).then(setProfile).catch((error) => setNotice(error.message)); }, [id]);
  const update = async (moduleCode, status) => { setBusy(true); try { await call(`/api/corrections/contributors/${id}/development`, "PATCH", { moduleCode, status }); setProfile(await call(`/api/corrections/contributors/${id}/development`)); setNotice("Staff development record saved."); } catch (error) { setNotice(error.message); } finally { setBusy(false); } };
  return <main className={styles.page}><header className={styles.hero}><span>RUVANAS INSIDE · CONTRIBUTORS</span><h1>Support production skills</h1><p>Staff record internal development milestones. Studio activity is evidence, not automatic completion or an accredited qualification.</p></header>
    {notice && <p role="status" className={styles.notice}>{notice}</p>}
    <nav className={styles.links}><a href="/dashboard/corrections">Facilities</a><a href="/dashboard/corrections/studio">Supervised Studio</a><a href="/dashboard/corrections/requests">Requests</a><a href="/dashboard/corrections/rehabilitation">Rehabilitation</a></nav>
    <section className={styles.card}><h2>Contributor profile</h2><label>Choose contributor<select value={id} onChange={(event) => { setId(event.target.value); setProfile(null); }}><option value="">Choose contributor</option>{contributors.map((item) => <option key={item.id} value={item.id}>{item.displayName} · {item.status}</option>)}</select></label>
      {profile && <><div className={styles.stats}><span>{profile.evidence.supervisedSessionCount} recent supervised sessions</span><span>{(profile.evidence.supervisedMinutes / 60).toFixed(1)} recent supervised hours</span><span>{profile.evidence.submittedProductions} recent submissions</span><span>{profile.evidence.approvedProductions} recent approved productions</span><span>{profile.evidence.approvedProgrammes} approved programmes</span><span>{profile.evidence.modulesCompleted} modules completed by staff</span></div>
      <div className={styles.fields}><details><summary>Recent supervised Studio sessions</summary>{profile.sessions.slice(0, 10).map((session) => <p key={session.id}>{session.status} · {new Date(session.activatedAt || session.completedAt || session.expiresAt).toLocaleDateString()}</p>)}{!profile.sessions.length && <p>No supervised sessions yet.</p>}</details><details><summary>Submissions and staff decisions</summary>{profile.submissions.slice(0, 10).map((submission) => <p key={submission.id}>Revision {submission.revision} · {submission.status} · {new Date(submission.submittedAt).toLocaleDateString()}</p>)}{!profile.submissions.length && <p>No submissions yet.</p>}</details><details><summary>Linked programmes</summary>{profile.programmes.map((programme) => <p key={programme.id}>{programme.title} · {programme.status}</p>)}{!profile.programmes.length && <p>No linked programmes yet.</p>}</details></div><p>No confidential correctional records are shown.</p></>}
    </section>
    {profile && <section className={styles.card}><h2>Development pathway</h2>{profile.canConfigureModules && <div className={styles.fields}><label>Add a local module<input value={newModule} onChange={(event) => setNewModule(event.target.value)} maxLength={80} /></label><button disabled={busy || newModule.trim().length < 3} onClick={async () => { setBusy(true); try { await call("/api/corrections/development/modules", "POST", { title: newModule }); setNewModule(""); setProfile(await call(`/api/corrections/contributors/${id}/development`)); setNotice("Module added to this organisation."); } catch (error) { setNotice(error.message); } finally { setBusy(false); } }}>Add module</button></div>}<div className={styles.list}>{profile.pathway.map((item) => <div key={item.code} className={styles.evidence}><strong>{item.position}. {item.title}</strong><p>{item.record.status.replaceAll("_", " ")}{item.record.completedAt ? ` · ${new Date(item.record.completedAt).toLocaleDateString()}` : ""}</p>{profile.canEdit && <div className={styles.actions}><button disabled={busy} onClick={() => update(item.code, "IN_PROGRESS")}>In progress</button><button disabled={busy} onClick={() => update(item.code, "COMPLETED")}>Mark complete</button><button disabled={busy} onClick={() => update(item.code, "NOT_STARTED")}>Reset</button></div>}</div>)}</div><p className={styles.caution}>Only authorised facility staff can change a milestone. These are internal records, not certificates.</p></section>}
  </main>;
}
