"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

const weekdays=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const emptySlot=()=>({weekday:1,startsAt:"09:00",endsAt:"17:00",musicModeId:"",priority:0});

export default function NewMusicScheduleForm({ organisations, locations, modes }) {
  const router=useRouter();
  const [form,setForm]=useState({organisationId:"",targetType:"LOCATION",targetId:"",name:"",effectiveFrom:"",effectiveTo:"",publish:false});
  const [slots,setSlots]=useState([emptySlot()]); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  const availableLocations=useMemo(()=>locations.filter((item)=>item.organisationId===form.organisationId),[locations,form.organisationId]);
  const targets=useMemo(()=>form.targetType==="LOCATION"?availableLocations:availableLocations.flatMap((location)=>location.zones.map((zone)=>({id:zone.id,name:`${location.name} / ${zone.name}`,timezone:location.timezone}))),[availableLocations,form.targetType]);
  const availableModes=useMemo(()=>modes.filter((mode)=>mode.organisationId===form.organisationId),[modes,form.organisationId]);
  function field(event){const {name,value,type,checked}=event.target;setForm((current)=>({...current,[name]:type==="checkbox"?checked:value,...(name==="organisationId"||name==="targetType"?{targetId:""}:{})}));}
  function slotField(index,event){setSlots((current)=>current.map((slot,i)=>i===index?{...slot,[event.target.name]:event.target.name==="weekday"||event.target.name==="priority"?Number(event.target.value):event.target.value}:slot));}
  async function submit(event){event.preventDefault();setSaving(true);setError("");try{const response=await fetch("/api/admin/music-schedules",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,slots})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to create the schedule.");router.push("/admin/music-schedules");router.refresh();}catch(submitError){setError(submitError instanceof Error?submitError.message:"Unable to create the schedule.");}finally{setSaving(false);}}
  return <main style={styles.page}><p style={styles.eyebrow}>Radio Control</p><h1 style={styles.title}>Create music schedule</h1><p style={styles.help}>Times remain in the selected location’s timezone when daylight-saving clocks change. Publishing replaces the currently published version for the same target.</p>{error?<div style={styles.error}>{error}</div>:null}<form onSubmit={submit} style={styles.form}>
    <label style={styles.label}>Organisation<select required name="organisationId" value={form.organisationId} onChange={field} style={styles.input}><option value="">Choose an organisation</option>{organisations.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
    <label style={styles.label}>Schedule name<input required maxLength={120} name="name" value={form.name} onChange={field} style={styles.input}/></label>
    <div style={styles.columns}><label style={styles.label}>Target type<select name="targetType" value={form.targetType} onChange={field} style={styles.input}><option value="LOCATION">Whole location</option><option value="ZONE">Specific zone</option></select></label><label style={styles.label}>Target<select required name="targetId" value={form.targetId} onChange={field} style={styles.input}><option value="">Choose a target</option>{targets.map((item)=><option key={item.id} value={item.id}>{item.name} ({item.timezone})</option>)}</select></label></div>
    <div style={styles.columns}><label style={styles.label}>Effective from (optional)<input type="date" name="effectiveFrom" value={form.effectiveFrom} onChange={field} style={styles.input}/></label><label style={styles.label}>Effective to (optional)<input type="date" name="effectiveTo" value={form.effectiveTo} onChange={field} style={styles.input}/></label></div>
    <fieldset style={styles.fieldset}><legend style={styles.legend}>Weekly slots</legend>{slots.map((slot,index)=><div key={index} style={styles.slot}><select aria-label={`Weekday ${index+1}`} name="weekday" value={slot.weekday} onChange={(event)=>slotField(index,event)} style={styles.input}>{weekdays.map((day,i)=><option key={day} value={i}>{day}</option>)}</select><input aria-label={`Start ${index+1}`} type="time" name="startsAt" value={slot.startsAt} onChange={(event)=>slotField(index,event)} style={styles.input}/><input aria-label={`End ${index+1}`} type="time" name="endsAt" value={slot.endsAt} onChange={(event)=>slotField(index,event)} style={styles.input}/><select aria-label={`Music mode ${index+1}`} required name="musicModeId" value={slot.musicModeId} onChange={(event)=>slotField(index,event)} style={styles.input}><option value="">Music mode</option>{availableModes.map((mode)=><option key={mode.id} value={mode.id}>{mode.name} ({mode.status})</option>)}</select><input aria-label={`Priority ${index+1}`} type="number" min="0" max="100" name="priority" value={slot.priority} onChange={(event)=>slotField(index,event)} style={styles.small}/><button type="button" onClick={()=>setSlots((current)=>current.filter((_,i)=>i!==index))} disabled={slots.length===1}>Remove</button></div>)}<button type="button" onClick={()=>setSlots((current)=>[...current,emptySlot()])} style={styles.secondary}>Add slot</button></fieldset>
    <label style={styles.check}><input type="checkbox" name="publish" checked={form.publish} onChange={field}/> Publish immediately (all selected music modes must be active)</label>
    <div style={styles.actions}><button disabled={saving} style={styles.button}>{saving?"Saving…":form.publish?"Publish schedule":"Create draft"}</button><Link href="/admin/music-schedules">Cancel</Link></div>
  </form></main>;
}

const styles={page:{maxWidth:980,margin:"0 auto",padding:"40px 16px 64px",color:"#172033"},eyebrow:{margin:"0 0 8px",color:"#9a6400",fontWeight:900,textTransform:"uppercase"},title:{margin:0,fontSize:32},help:{color:"#475569",lineHeight:1.55},error:{padding:12,background:"#fef2f2",border:"1px solid #fca5a5",borderRadius:7,color:"#991b1b"},form:{display:"grid",gap:18,marginTop:24,padding:24,border:"1px solid #cbd5e1",borderRadius:12,background:"#f8fafc"},label:{display:"grid",gap:7,fontWeight:800},input:{padding:10,border:"1px solid #94a3b8",borderRadius:7,font:"inherit",background:"#fff",minWidth:0},small:{padding:10,border:"1px solid #94a3b8",borderRadius:7,width:72},columns:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:16},fieldset:{border:"1px solid #cbd5e1",borderRadius:8,padding:16},legend:{fontWeight:900},slot:{display:"grid",gridTemplateColumns:"1fr 130px 130px 1.5fr 80px auto",gap:8,marginBottom:10,alignItems:"center"},secondary:{padding:"8px 12px",fontWeight:800},check:{display:"flex",gap:9,alignItems:"center",fontWeight:800},actions:{display:"flex",gap:16,alignItems:"center"},button:{border:0,borderRadius:7,background:"#f4b942",color:"#172033",padding:"11px 15px",fontWeight:900,cursor:"pointer"}};
