"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./studio-pro.module.css";

const libraryTabs = ["ALL", "MUSIC", "JINGLE", "PROMO", "ADVERT", "PROGRAMME", "PODCAST", "INTERVIEW", "NEWS", "EFFECT"];
const programmeRoles = ["INTRO", "OUTRO", "JINGLE", "BED", "PROMO", "PRERECORDED_SEGMENT", "INTERVIEW", "RECURRING_FEATURE"];
const commandKey = (action) => `studio-playout:${action}:${crypto.randomUUID()}`;
const durationLabel = (milliseconds) => { const seconds = Math.max(0, Math.round(Number(milliseconds || 0) / 1000)); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`; };

function PrepareEditor({ item, busy, act }) {
  const [values, setValues] = useState({ title: item.title, artistOrProgramme: item.artistOrProgramme || "", itemType: item.itemType, cueInMs: item.cueInMs || 0, cueOutMs: item.cueOutMs || "", fadeInMs: item.fadeInMs || 0, fadeOutMs: item.fadeOutMs || 0, gainDb: item.gainDb || 0 });
  const field = (name, number = false) => ({ value: values[name], onChange: (event) => setValues((current) => ({ ...current, [name]: number ? Number(event.target.value) : event.target.value })) });
  return <div className={styles.item}><header><strong>{item.title}</strong><span className={styles.status}>{item.rightsReady ? "READY" : "BLOCKED"}</span></header><p>{item.readinessReason}</p><div className={styles.prepareFields}><label>Title<input {...field("title")} /></label><label>Artist / programme<input {...field("artistOrProgramme")} /></label><label>Type<input {...field("itemType")} /></label><label>Cue in (ms)<input type="number" min="0" {...field("cueInMs", true)} /></label><label>Cue out (ms)<input type="number" min="1" value={values.cueOutMs} onChange={(event) => setValues((current) => ({ ...current, cueOutMs: event.target.value ? Number(event.target.value) : null }))} /></label><label>Gain (dB)<input type="number" min="-18" max="12" step=".5" {...field("gainDb", true)} /></label><label>Fade in (ms)<input type="number" min="0" {...field("fadeInMs", true)} /></label><label>Fade out (ms)<input type="number" min="0" {...field("fadeOutMs", true)} /></label></div><div className={styles.actions}><a className={styles.secondary} href={`/api/media/${item.mediaAssetId}/stream`} target="_blank" rel="noreferrer">Local preview</a><button className={styles.secondary} disabled={busy} onClick={() => act("UPDATE_PREPARE", { itemId: item.id, ...values, cueOutMs: values.cueOutMs || null })}>Save preparation</button><button className={styles.button} disabled={busy || !item.rightsReady} onClick={() => act("SEND_NEXT", { itemId: item.id })}>Send to Next</button><button className={styles.secondary} disabled={busy || !item.rightsReady} onClick={() => act("INSERT_QUEUE", { itemId: item.id })}>Add to end</button><a className={styles.secondary} href="/dashboard/studio">Open in Waveform Pro</a></div></div>;
}

export default function ManualPlayoutClient({ enabled }) {
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [libraryTab, setLibraryTab] = useState("ALL"); const [clockMs, setClockMs] = useState(Date.now());
  const load = useCallback(async () => { if (!enabled) return; const response = await fetch("/api/studio/playout", { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Manual Playout could not be loaded."); setData(body); }, [enabled]);
  useEffect(() => { load().catch((e) => setError(e.message)); }, [load]);
  useEffect(() => { const timer = window.setInterval(() => setClockMs(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  const session = data?.sessions?.find((item) => item.status === "ACTIVE") || data?.sessions?.[0] || null;
  const live = useMemo(() => (session?.items || []).filter((item) => item.area === "LIVE" || item.status === "ON_AIR").sort((a,b) => a.position-b.position), [session]);
  const prepare = useMemo(() => (session?.items || []).filter((item) => item.area === "PREPARE"), [session]);
  const onAir = live.find((item) => item.status === "ON_AIR") || null;
  const elapsedMs = onAir?.startedAt ? Math.max(0, clockMs - new Date(onAir.startedAt).getTime()) : 0;
  const remainingMs = onAir?.durationMs ? Math.max(0, onAir.durationMs - elapsedMs) : 0;
  const progress = onAir?.durationMs ? Math.min(100, (elapsedMs / onAir.durationMs) * 100) : 0;
  const estimatedRuntimeMinutes = useMemo(() => Math.round(live.reduce((total, item) => total + Number(item.durationMs || 0), 0) / 60000), [live]);
  const filteredAssets = useMemo(() => (data?.assets || []).filter((asset) => libraryTab === "ALL" || asset.mediaType === libraryTab || (libraryTab === "MUSIC" && asset.licensed)), [data, libraryTab]);
  async function act(action, extra = {}) { setBusy(true); setError(""); setNotice(""); try { const response = await fetch("/api/studio/playout", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": commandKey(action) }, body: JSON.stringify({ action, ...(session && action !== "CREATE_SESSION" ? { sessionId: session.id, expectedRevision: session.revision } : {}), ...extra }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "The playout command failed."); setNotice(`${action.replaceAll("_", " ")} completed.`); await load(); return body; } catch (e) { setError(e.message); return null; } finally { setBusy(false); } }
  async function create(event) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); await act("CREATE_SESSION", values); }
  async function addAsset(assetId) { if (!session) return; await act("ADD_PREPARE", { mediaAssetId: assetId }); }
  async function createPack(event) { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); if (await act("CREATE_PACK", values)) form.reset(); }
  async function addPackItem(event) { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); if (await act("ADD_PACK_ITEM", values)) form.reset(); }
  if (!enabled) return <section className={`${styles.panel} ${styles.locked}`}><div><p className={styles.eyebrow}>STUDIO PRO</p><h2>Manual Playout is available on Tiers 3–5</h2><p className={styles.muted}>Your Studio Basic projects remain available. Upgrade to prepare a recoverable live queue while AutoDJ stays armed as fallback.</p></div></section>;
  if (!data) return <section className={styles.panel}><p>{error || "Loading Manual Playout…"}</p></section>;
  return <section className={styles.panel}>
    <div className={styles.topbar}><div><p className={styles.eyebrow}>SERVER-AUTHORITATIVE PLAYOUT</p><h2>{session?.title || "Manual Playout"}</h2><div className={styles.health}><span>Mode: <strong>{session?.mode || "AUTO"}</strong></span><span>Output: <strong>{session?.outputHealth || "Ready"}</strong></span><span>Clock: <strong>{new Date(clockMs).toLocaleTimeString()}</strong></span><span>Queue: <strong>{live.filter((item) => item.status === "READY").length}</strong></span><span>Estimated runtime: <strong>{estimatedRuntimeMinutes} min</strong></span></div></div>{session ? <select aria-label="Playout mode" value={session.mode} onChange={(event) => act("SET_MODE", { mode: event.target.value })} disabled={busy}><option>AUTO</option><option>ASSIST</option><option>MANUAL</option></select> : null}{session ? <button className={styles.danger} disabled={busy} onClick={() => act("END_SESSION")}>End manual session</button> : null}</div>
    {error ? <div className={styles.error}>{error}</div> : null}{notice ? <div className={styles.notice}>{notice}</div> : null}
    {!session ? <form className={`${styles.card} ${styles.form}`} onSubmit={create}><h3>Create a protected playout session</h3><label>Session title<input name="title" required minLength="2" /></label><label>Channel<select name="channelId" required><option value="">Choose an active channel with AutoDJ fallback</option>{data.channels.map((channel) => <option key={channel.id} value={channel.id}>{channel.name} · {channel.autoDjPolicy?.enabled && channel.autoDjPolicy?.state === "ACTIVE" ? "fallback ready" : "fallback required"}</option>)}</select></label><button className={styles.button} disabled={busy}>Create session</button></form> : <><section className={styles.nowPlaying}><div><p className={styles.eyebrow}>NOW PLAYING</p><h3>{onAir?.title || "AutoDJ or schedule is holding the output"}</h3><p>{onAir?.artistOrProgramme || (session.outputHealth === "SCHEDULED_PRIORITY" ? "A priority schedule item has control; your manual queue is preserved." : session.outputHealth)}</p></div><div className={styles.waveform} aria-label={`Playback progress ${Math.round(progress)} percent`}><span style={{ width: `${progress}%` }} /></div><strong>{durationLabel(elapsedMs)} / -{durationLabel(remainingMs)}</strong></section><div className={styles.grid3}>
      <article className={styles.card} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); const mediaAssetId = e.dataTransfer.getData("text/media-asset"); if (mediaAssetId) act("ADD_LIVE", { mediaAssetId }); }}><p className={styles.eyebrow}>LIVE PLAYLIST</p><h3>On air and next</h3>{live.filter((item) => item.status === "READY").length <= 2 ? <p className={styles.warning}>Low queue — AutoDJ fallback remains armed.</p> : null}<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={() => act("START_NEXT")}>Start next</button><button className={styles.secondary} disabled={busy} onClick={() => act("FADE")}>Fade to next</button><button className={styles.secondary} disabled={busy} onClick={() => act("SKIP")}>Skip</button></div><div className={styles.list}>{!live.length ? <p className={styles.muted}>Drop media here. An empty queue returns to AutoDJ rather than creating dead air.</p> : live.map((item, index) => { const priorMs = live.filter((candidate) => candidate.status === "READY").slice(0, Math.max(0, index)).reduce((sum, candidate) => sum + Number(candidate.durationMs || 0), remainingMs); return <div className={styles.item} key={item.id}><header><strong>{item.status === "ON_AIR" ? "ON AIR" : index === (onAir ? 1 : 0) ? "NEXT" : `#${index + 1}`} · {item.title}</strong><span className={styles.status}>{item.rightsReady ? "READY" : "BLOCKED"}</span></header><p>{item.artistOrProgramme || item.itemType} · {durationLabel(item.durationMs)}{item.status === "READY" ? ` · est. ${new Date(clockMs + priorMs).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}` : ` · ${durationLabel(remainingMs)} remaining`}</p><div className={styles.actions}>{item.status === "READY" ? <><button className={styles.secondary} disabled={busy || item.locked} onClick={() => act("REORDER", { itemId: item.id, position: Math.max(0,index-1) })}>Move up</button><button className={styles.secondary} disabled={busy} onClick={() => act("LOCK", { itemId: item.id, locked: !item.locked })}>{item.locked ? "Unlock" : "Lock"}</button></> : null}</div></div>; })}</div></article>
      <article className={styles.card} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); addAsset(e.dataTransfer.getData("text/media-asset")); }}><p className={styles.eyebrow}>PREPARE</p><h3>Private staging</h3><p className={styles.muted}>Preview, edit metadata, set cue points, fades and gain here. Nothing enters public output until you send it.</p><div className={styles.list}>{!prepare.length ? <p className={styles.muted}>Drag media here or choose Prepare from the library.</p> : prepare.map((item) => <PrepareEditor key={item.id} item={item} busy={busy} act={act} />)}</div><form className={styles.form} onSubmit={createPack}><h3>Programme pack</h3><label>Name<input name="title" placeholder="Morning Show" required /></label><label>Description<textarea name="description" /></label><button className={styles.secondary} disabled={busy}>Create pack</button></form>{data.packs.length ? <form className={styles.form} onSubmit={addPackItem}><h3>Add protected media to a pack</h3><label>Pack<select name="packId" required><option value="">Choose pack</option>{data.packs.map((pack) => <option key={pack.id} value={pack.id}>{pack.name} · {pack.items.length} items</option>)}</select></label><label>Media<select name="mediaAssetId" required><option value="">Choose protected media</option>{data.assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.artist ? `${asset.artist} — ${asset.title}` : asset.name}</option>)}</select></label><label>Role<select name="role" required>{programmeRoles.map((role) => <option key={role} value={role}>{role.replaceAll("_", " ")}</option>)}</select></label><button className={styles.secondary} disabled={busy}>Add reference</button><p className={styles.muted}>Programme Packs reference existing protected media; they never copy source files.</p></form> : null}</article>
      <article className={styles.card}><p className={styles.eyebrow}>LIBRARY</p><h3>Protected media</h3><div className={styles.libraryTabs}>{libraryTabs.map((name) => <button key={name} type="button" aria-pressed={libraryTab === name} onClick={() => setLibraryTab(name)}>{name.replaceAll("_", " ")}</button>)}</div><div className={styles.list}>{filteredAssets.map((asset) => <div className={styles.item} key={asset.id} draggable onDragStart={(e) => e.dataTransfer.setData("text/media-asset", asset.id)}><header><strong>{asset.artist ? `${asset.artist} — ${asset.title}` : asset.name}</strong>{asset.licensed ? <span className={styles.status}>LICENSED</span> : null}</header><p>{asset.mediaType} · {asset.durationSeconds || "?"} sec</p><button className={styles.secondary} disabled={busy} onClick={() => addAsset(asset.id)}>Prepare</button></div>)}</div></article>
    </div></>}
  </section>;
}
