"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./studio-pro.module.css";

export default function StudioBroadcastClient({ enabled }) {
  const [data,setData]=useState(null); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false); const [selected,setSelected]=useState([]);
  const load=useCallback(async()=>{if(!enabled)return;const response=await fetch("/api/studio/broadcast",{cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Studio Broadcast could not be loaded.");setData(body);},[enabled]);
  useEffect(()=>{load().catch((e)=>setError(e.message));},[load]);
  const active=useMemo(()=>(data?.sessions||[]).find((item)=>item.status==="ACTIVE")||null,[data]);
  async function act(action,extra={}){setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/studio/broadcast",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":`studio-broadcast:${action}:${crypto.randomUUID()}`},body:JSON.stringify({action,...extra})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"The broadcast command failed.");setNotice(body.notice||`${action.replaceAll("_"," ")} completed.`);await load();return body;}catch(e){setError(e.message);return null;}finally{setBusy(false);}}
  async function createExternal(event){event.preventDefault();const form=event.currentTarget;const raw=Object.fromEntries(new FormData(form).entries());const payload={...raw,port:Number(raw.port),bitrateKbps:Number(raw.bitrateKbps),isBackup:raw.isBackup==="on"};if(await act("CREATE_EXTERNAL",payload))form.reset();}
  if(!enabled)return <section className={`${styles.panel} ${styles.locked}`}><div><p className={styles.eyebrow}>STUDIO PRO</p><h2>Live Broadcast & Distribution is available on Tiers 3–5</h2><p className={styles.muted}>Studio Basic can still render rights-safe files. External destinations and Manual Playout remain locked without changing saved projects or destination profiles.</p></div></section>;
  if(!data)return <section className={styles.panel}><p>{error||"Loading Studio Broadcast…"}</p></section>;
  return <section className={styles.panel}><div className={styles.topbar}><div><p className={styles.eyebrow}>SERVER-SIDE DISTRIBUTION CONTROL</p><h2>Live Broadcast & Distribution</h2><p className={styles.muted}>This browser monitors and controls output. Closing it does not stop the server programme.</p></div><span className={styles.status}>{data.providerConfigured?"EXTERNAL PROVIDER READY":"MANAGED STREAMS ONLY"}</span><strong>{data.externalDestinationLimit} external destinations</strong></div>{error?<div className={styles.error}>{error}</div>:null}{notice?<div className={styles.notice}>{notice}</div>:null}
    <div className={styles.destinationGrid}><article className={styles.card}><h3>Ruvanas Quick Connect</h3><p className={styles.muted}>Uses the station already held securely by Ruvanas. No hostname, port or password needs to be re-entered.</p>{data.stations.map((station)=><div className={styles.item} key={station.id}><header><strong>{station.name}</strong><span className={styles.status}>{station.streamConfig.sourceConnectionStatus}</span></header><p>{station.streamConfig.serverType} · {station.streamConfig.outputCodec} · {station.streamConfig.bitrateKbps||"default"} kbps</p><button className={styles.button} disabled={busy} onClick={()=>act("QUICK_CONNECT",{stationId:station.id})}>Connect to My Ruvanas Station</button></div>)}</article>
      <form className={`${styles.card} ${styles.form}`} onSubmit={createExternal}><h3>External destination profile</h3><p className={styles.muted}>Icecast and SHOUTcast profiles connect only when compatible server infrastructure is configured.</p><div className={styles.two}><label>Name<input name="name" required /></label><label>Type<select name="type"><option>ICECAST</option><option>SHOUTCAST</option></select></label></div><div className={styles.two}><label>Host<input name="host" required /></label><label>Port<input name="port" type="number" min="1" max="65535" required /></label></div><label>Mount or service identifier<input name="mountOrService" required /></label><div className={styles.two}><label>Codec<select name="codec"><option>MP3</option><option>AAC</option></select></label><label>Bitrate<select name="bitrateKbps" defaultValue="128"><option>64</option><option>96</option><option>128</option><option>160</option><option>192</option><option>256</option><option>320</option></select></label></div><label>Primary / backup group<input name="primaryGroup" placeholder="Main distribution" /></label><label>Source credential<input name="credential" type="password" autoComplete="new-password" required /></label><label><input name="isBackup" type="checkbox" /> Use as the backup in this group</label><button className={styles.button} disabled={busy}>Save encrypted profile</button></form></div>
      <article className={styles.card}><h3>Destination health</h3><div className={styles.list}>{!data.destinations.length?<p className={styles.muted}>No destinations yet.</p>:data.destinations.map((destination)=><div className={styles.item} key={destination.id}><header><label><input type="checkbox" checked={selected.includes(destination.id)} onChange={(event)=>setSelected((current)=>event.target.checked?[...current,destination.id]:current.filter((id)=>id!==destination.id))} /> <strong>{destination.name}</strong></label><span className={styles.status}>{destination.connectionState}</span></header><p>{destination.type} · {destination.codec} · {destination.bitrateKbps||"managed"} kbps · listeners {destination.listenerCount??"Unavailable"}</p>{destination.primaryGroup?<p>{destination.primaryGroup} · {destination.isBackup?"backup":"primary"}</p>:null}<small>Last connected: {destination.lastConnectedAt?new Date(destination.lastConnectedAt).toLocaleString():"Never"} · reconnect {destination.nextReconnectAt?new Date(destination.nextReconnectAt).toLocaleString():"not scheduled"}</small>{destination.lastSafeError?<p className={styles.warning}>{destination.lastSafeError}</p>:null}<div className={styles.actions}><button className={styles.secondary} disabled={busy} onClick={()=>act("SET_ENABLED",{destinationId:destination.id,enabled:!destination.enabled})}>{destination.enabled?"Disable":"Enable"}</button><span className={styles.status}>{destination.credentialStored?"CREDENTIAL STORED":"NO BROWSER CREDENTIAL"}</span></div></div>)}</div></article>
    <article className={styles.card}><h3>Authoritative broadcast session</h3>{active?<><p>Now Playing metadata: <strong>{active.metadataOverride||active.automaticMetadata||"Waiting for playout"}</strong></p><div className={styles.actions}><button className={styles.danger} disabled={busy} onClick={()=>act("STOP_BROADCAST",{sessionId:active.id,expectedRevision:active.revision})}>Stop safely</button><button className={styles.secondary} disabled={busy} onClick={()=>act("RESET_METADATA",{sessionId:active.id,expectedRevision:active.revision})}>Reset to Automatic</button></div><form className={`${styles.form} ${styles.two}`} onSubmit={(event)=>{event.preventDefault();act("SET_METADATA",{sessionId:active.id,expectedRevision:active.revision,metadata:new FormData(event.currentTarget).get("metadata")});}}><label>Temporary metadata<input name="metadata" required /></label><button className={styles.secondary} disabled={busy}>Set temporary override</button></form></>:<form className={`${styles.form} ${styles.two}`} onSubmit={(event)=>{event.preventDefault();act("START_BROADCAST",{playoutSessionId:new FormData(event.currentTarget).get("playoutSessionId"),destinationIds:selected});}}><label>Manual Playout session<select name="playoutSessionId" required><option value="">Choose active output</option>{data.playoutSessions.map((session)=><option key={session.id} value={session.id}>{session.title} · {session.mode}</option>)}</select></label><button className={styles.button} disabled={busy||!selected.length}>Start selected destinations</button></form>}</article>
  </section>;
}
