import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { hashPlayerToken } from "../../lib/player-tokens.mjs";
import { createPlaybackProofToken } from "../../lib/playback-proof.mjs";
import { correctionsRenderEvidence } from "../../lib/corrections-workflow.mjs";

const baseUrl = process.env.INTEGRATION_BASE_URL || "http://127.0.0.1:3105";
const secret = process.env.SESSION_SECRET;

async function api(path, { method = "GET", body, cookie, instanceId } = {}) {
  const response = await fetch(`${baseUrl}${path}`, { method, headers: { origin: baseUrl, ...(body ? { "content-type": "application/json" } : {}), ...(cookie ? { cookie } : {}), ...(instanceId ? { "x-ruvanas-player-instance": instanceId } : {}) }, body: body ? JSON.stringify(body) : undefined });
  return { status: response.status, body: await response.json(), cookie: response.headers.get("set-cookie")?.split(";")[0] };
}

test("C5.1 approved request and rehabilitation content use private signed playout intents and real completion proof", async () => {
  if (!/127\.0\.0\.1:55433\/ruvanas_c5/.test(process.env.DATABASE_URL || "") || !secret || secret.length < 32) throw new Error("C5.1 integration must use the isolated local database and test secret.");
  const db = new PrismaClient();
  const suffix = randomUUID().slice(0, 8);
  const password = `C51-local-${randomUUID()}!`;
  const token = `private-player-${randomUUID()}`;
  const instanceId = randomUUID();
  let organisation, plan, owner, manager, viewer, contributor, outsider, otherOrganisation;
  try {
    const hash = await bcrypt.hash(password, 4);
    plan = await db.plan.create({ data: { name: `C51 ${suffix}`, code: `C51_${suffix}`, productFamily: "CORRECTIONS", tierNumber: 2, monthlyPriceCents: 29900, storageLimitGb: 10, listenerLimit: 100, maxBitrateKbps: 128, correctionsRadioEnabled: true, stationLimit: 2 } });
    organisation = await db.organisation.create({ data: { name: `C51 ${suffix}`, slug: `c51-${suffix}` } });
    otherOrganisation = await db.organisation.create({ data: { name: `C51 other ${suffix}`, slug: `c51-other-${suffix}` } });
    await db.subscription.createMany({ data: [{ organisationId: organisation.id, planId: plan.id, status: "ACTIVE" }, { organisationId: otherOrganisation.id, planId: plan.id, status: "ACTIVE" }] });
    async function member(role, label, org) {
      const user = await db.user.create({ data: { name: label, email: `${label.toLowerCase()}-${suffix}@example.invalid`, passwordHash: hash, role } });
      await db.organisationMember.create({ data: { organisationId: org.id, userId: user.id, role } });
      return user;
    }
    owner = await member("OWNER", "C51Owner", organisation);
    manager = await member("MANAGER", "C51Manager", organisation);
    viewer = await member("VIEWER", "C51Viewer", organisation);
    contributor = await member("CONTENT_EDITOR", "C51Contributor", organisation);
    outsider = await member("OWNER", "C51Outsider", otherOrganisation);
    async function cookieFor(user) { const login = await api("/api/auth/login", { method: "POST", body: { email: user.email, password } }); assert.equal(login.status, 200, JSON.stringify(login.body)); return login.cookie; }
    const ownerCookie = await cookieFor(owner);
    const viewerCookie = await cookieFor(viewer);
    const contributorCookie = await cookieFor(contributor);
    const outsiderCookie = await cookieFor(outsider);

    const configuredAt = new Date();
    const location = await db.location.create({ data: { organisationId: organisation.id, name: "Synthetic private facility", slug: "synthetic-private-facility", status: "ACTIVE", timezone: "Europe/Malta", countryCode: "MT", zones: { create: { name: "Private wing", slug: "private-wing", status: "ACTIVE" } }, correctionsFacility: { create: { policyConfiguredAt: configuredAt, requestAvailability: "INTERNAL_ONLY", messageRequestsEnabled: true } } }, include: { zones: true } });
    await db.correctionsProfile.create({ data: { organisationId: organisation.id, policyConfiguredAt: configuredAt } });
    const zone = location.zones[0];
    const otherFacility = await db.location.create({ data: { organisationId: organisation.id, name: "Other private facility", slug: "other-private-facility", status: "ACTIVE", timezone: "Europe/Malta", countryCode: "MT", zones: { create: { name: "Other wing", slug: "other-wing", status: "ACTIVE" } }, correctionsFacility: { create: { policyConfiguredAt: configuredAt, requestAvailability: "INTERNAL_ONLY" } } }, include: { zones: true } });
    const station = await db.station.create({ data: { organisationId: organisation.id, productFamily: "CORRECTIONS", name: "Synthetic Inside", slug: `c51-inside-${suffix}`, status: "ACTIVE", listenerLimit: 10, storageLimitGb: 1, maxBitrateKbps: 128 } });
    const channel = await db.channel.create({ data: { organisationId: organisation.id, stationId: station.id, name: "Private channel", slug: `c51-private-${suffix}`, status: "ACTIVE", musicRightsUse: "CORRECTIONS_RADIO" } });
    await db.channelAssignment.create({ data: { channelId: channel.id, zoneId: zone.id, activeFrom: new Date(Date.now() - 60_000) } });
    const player = await db.player.create({ data: { organisationId: organisation.id, zoneId: zone.id, name: "Private test player", status: "ONLINE", sessionTokenHash: hashPlayerToken(token, secret), enrolledAt: new Date(), lastHeartbeatAt: new Date() } });
    const playerCookie = `ruvanas_player=${token}`;
    const otherPlayerToken = `other-facility-${randomUUID()}`;
    await db.player.create({ data: { organisationId: organisation.id, zoneId: otherFacility.zones[0].id, name: "Other facility player", status: "ONLINE", sessionTokenHash: hashPlayerToken(otherPlayerToken, secret), enrolledAt: new Date(), lastHeartbeatAt: new Date() } });

    const checksum = "a".repeat(64);
    const media = await db.mediaAsset.create({ data: { organisationId: organisation.id, libraryType: "ORGANISATION_PROMO", name: "Approved programme audio", originalName: "synthetic.mp3", storageKey: `c51-test/${suffix}/programme.mp3`, mimeType: "audio/mpeg", sizeBytes: BigInt(1024), durationSeconds: 60, mediaType: "ANNOUNCEMENT", status: "READY" } });
    const promoAsset = await db.promoAsset.create({ data: { organisationId: organisation.id, name: "Approved programme", mediaType: "ANNOUNCEMENT" } });
    const promoVersion = await db.promoVersion.create({ data: { promoAssetId: promoAsset.id, mediaAssetId: media.id, version: 1, status: "APPROVED", qcStatus: "PASSED", checksumSha256: checksum } });
    const project = await db.audioProject.create({ data: { organisationId: organisation.id, title: "Synthetic programme", editDecision: {}, createdByUserId: owner.id } });
    const version = await db.audioProjectVersion.create({ data: { projectId: project.id, version: 1, state: {}, createdByUserId: owner.id } });
    const render = await db.audioRender.create({ data: { organisationId: organisation.id, projectId: project.id, versionId: version.id, outputMediaAssetId: media.id, outputPromoVersionId: promoVersion.id, requestedByUserId: owner.id, preset: "SPEECH_MP3", status: "SUCCEEDED", completedAt: new Date(), resultJson: { checksumSha256: checksum } } });
    const renderEvidence = correctionsRenderEvidence(await db.audioRender.findUnique({ where: { id: render.id }, include: { outputMediaAsset: true, outputPromoVersion: true, version: { select: { state: true } }, project: { select: { organisationId: true, createdByUserId: true, currentVersion: true, title: true } } } }));
    const programme = await db.correctionsProgramme.create({ data: { organisationId: organisation.id, facilityId: location.id, title: "Synthetic request and rehabilitation programme", createdByUserId: owner.id, status: "APPROVED", latestRevision: 1 } });
    const submission = await db.correctionsSubmission.create({ data: { programmeId: programme.id, organisationId: organisation.id, facilityId: location.id, revision: 1, renderId: render.id, sourceFingerprint: renderEvidence.fingerprint, organisationPolicyVersion: 1, facilityPolicyVersion: 1, titleSnapshot: programme.title, evidenceSnapshot: renderEvidence, submittedByUserId: owner.id, status: "APPROVED" } });
    await db.correctionsReview.create({ data: { submissionId: submission.id, stage: "STAFF", decision: "APPROVE", note: "Synthetic test approval", evidenceSnapshot: {}, reviewedByUserId: manager.id } });
    const rehabMedia = await db.mediaAsset.create({ data: { organisationId: organisation.id, libraryType: "ORGANISATION_PROMO", name: "Approved education audio", originalName: "education.mp3", storageKey: `c51-test/${suffix}/education.mp3`, mimeType: "audio/mpeg", sizeBytes: BigInt(1024), durationSeconds: 45, mediaType: "ANNOUNCEMENT", status: "READY" } });
    const rehabPromo = await db.promoAsset.create({ data: { organisationId: organisation.id, name: "Education audio", mediaType: "ANNOUNCEMENT" } });
    await db.promoVersion.create({ data: { promoAssetId: rehabPromo.id, mediaAssetId: rehabMedia.id, version: 1, status: "APPROVED", qcStatus: "PASSED" } });
    const category = await db.correctionsRehabCategory.create({ data: { organisationId: organisation.id, code: "EDUCATION", name: "Education" } });
    const rehab = await db.correctionsRehabContent.create({ data: { organisationId: organisation.id, facilityId: location.id, categoryId: category.id, mediaAssetId: rehabMedia.id, title: "Synthetic education", providerName: "Test provider", status: "APPROVED", createdByUserId: owner.id, reviewedByUserId: manager.id, reviewedAt: new Date() } });
    await db.correctionsRehabProgrammeItem.create({ data: { programmeId: programme.id, contentId: rehab.id, position: 1, addedByUserId: owner.id } });

    const created = await api("/api/corrections/requests", { method: "POST", cookie: ownerCookie, body: { facilityId: location.id, type: "PROGRAMME", songTitle: "Synthetic request programme" } });
    assert.equal(created.status, 201, JSON.stringify(created.body));
    const requestId = created.body.request.id;
    const startsAt = new Date(Date.now() + 6 * 60_000).toISOString();
    const schedulePath = `/api/corrections/requests/${requestId}/schedule`;
    assert.equal((await api(schedulePath, { method: "POST", cookie: ownerCookie, body: { zoneId: zone.id, programmeId: programme.id, startsAt } })).status, 409);
    const rejectedCreate = await api("/api/corrections/requests", { method: "POST", cookie: ownerCookie, body: { facilityId: location.id, type: "PROGRAMME", songTitle: "Rejected request" } });
    assert.equal(rejectedCreate.status, 201);
    const rejectedPath = `/api/corrections/requests/${rejectedCreate.body.request.id}`;
    assert.equal((await api(rejectedPath, { method: "POST", cookie: ownerCookie, body: { action: "SCREEN" } })).status, 200);
    assert.equal((await api(rejectedPath, { method: "POST", cookie: ownerCookie, body: { action: "REJECT", note: "Not suitable for this programme" } })).status, 200);
    assert.equal((await api(`${rejectedPath}/schedule`, { method: "POST", cookie: ownerCookie, body: { zoneId: zone.id, programmeId: programme.id, startsAt } })).status, 409);
    await db.correctionsFacility.update({ where: { locationId: location.id }, data: { songRequestsEnabled: true } });
    const songMedia = await db.mediaAsset.create({ data: { organisationId: organisation.id, libraryType: "ORGANISATION_MUSIC", name: "Cleared song", originalName: "song.mp3", storageKey: `c51-test/${suffix}/song.mp3`, mimeType: "audio/mpeg", sizeBytes: BigInt(1024), durationSeconds: 120, mediaType: "MUSIC", status: "READY" } });
    const song = await db.track.create({ data: { mediaAssetId: songMedia.id, title: "Cleared song", artist: "Test artist", status: "READY", isExplicit: false, rightsHolder: "Test licensor", rightsReference: "C51 synthetic", rightsBasis: "DIRECT_LICENCE", permittedTerritories: "MT", permittedUses: ["CORRECTIONS_RADIO"], rightsConfirmedAt: configuredAt, rightsReviewStatus: "APPROVED" } });
    const songCreate = await api("/api/corrections/requests", { method: "POST", cookie: ownerCookie, body: { facilityId: location.id, type: "SONG", songTitle: song.title } });
    assert.equal(songCreate.status, 201, JSON.stringify(songCreate.body));
    const songPath = `/api/corrections/requests/${songCreate.body.request.id}`;
    assert.equal((await api(songPath, { method: "POST", cookie: ownerCookie, body: { action: "SCREEN" } })).status, 200);
    const songApproval = await api(songPath, { method: "POST", cookie: ownerCookie, body: { action: "APPROVE", trackId: song.id, programmeId: programme.id } });
    assert.equal(songApproval.status, 200, JSON.stringify(songApproval.body));
    await db.correctionsFacility.update({ where: { locationId: location.id }, data: { blockedTrackIds: [song.id] } });
    assert.equal((await api(`${songPath}/schedule`, { method: "POST", cookie: ownerCookie, body: { zoneId: zone.id, programmeId: programme.id, startsAt } })).status, 409);
    await db.correctionsFacility.update({ where: { locationId: location.id }, data: { blockedTrackIds: [] } });
    await db.track.update({ where: { id: song.id }, data: { status: "ARCHIVED" } });
    assert.equal((await api(`${songPath}/schedule`, { method: "POST", cookie: ownerCookie, body: { zoneId: zone.id, programmeId: programme.id, startsAt } })).status, 409);
    assert.equal((await api(`/api/corrections/requests/${requestId}`, { method: "POST", cookie: ownerCookie, body: { action: "SCREEN" } })).status, 200);
    assert.equal((await api(`/api/corrections/requests/${requestId}`, { method: "POST", cookie: ownerCookie, body: { action: "APPROVE", programmeId: programme.id } })).status, 200);
    assert.equal((await api(schedulePath, { method: "POST", cookie: viewerCookie, body: { zoneId: zone.id, programmeId: programme.id, startsAt } })).status, 403);
    assert.equal((await api(schedulePath, { method: "POST", cookie: contributorCookie, body: { zoneId: zone.id, programmeId: programme.id, startsAt } })).status, 403);
    assert.equal((await api(schedulePath, { method: "POST", cookie: outsiderCookie, body: { zoneId: zone.id, programmeId: programme.id, startsAt } })).status, 404);
    assert.equal((await api(schedulePath, { method: "POST", cookie: ownerCookie, body: { zoneId: otherFacility.zones[0].id, programmeId: programme.id, startsAt } })).status, 409);
    assert.equal((await api(schedulePath, { method: "POST", cookie: ownerCookie, body: { zoneId: randomUUID(), programmeId: programme.id, startsAt } })).status, 409);
    const scheduled = await api(schedulePath, { method: "POST", cookie: ownerCookie, body: { zoneId: zone.id, programmeId: programme.id, startsAt } });
    assert.equal(scheduled.status, 200, JSON.stringify(scheduled.body));
    assert.equal(scheduled.body.delivery.status, "SCHEDULED");
    assert.equal((await api(schedulePath, { method: "POST", cookie: ownerCookie, body: { zoneId: zone.id, programmeId: programme.id, startsAt } })).body.delivery.alreadyScheduled, true);
    assert.equal((await db.correctionsRequest.findUnique({ where: { id: requestId } })).status, "SCHEDULED");
    assert.equal(await db.proofOfPlayEvent.count({ where: { organisationId: organisation.id } }), 0);
    await db.playoutIntent.updateMany({ where: { correctionsRequestId: requestId }, data: { plannedStart: new Date(Date.now() - 4 * 60_000), expiresAt: new Date(Date.now() + 90_000) } });
    const manifest = await api("/api/player/manifest", { cookie: playerCookie, instanceId });
    assert.equal(manifest.status, 200, JSON.stringify(manifest.body));
    const insertion = manifest.body.insertions.find((item) => item.programmingSource === "CORRECTIONS_REQUEST");
    assert.ok(insertion?.proofToken, JSON.stringify(manifest.body.insertions));
    assert.equal(JSON.stringify(insertion).includes("recipient"), false);
    const proof = { eventId: randomUUID(), manifestVersion: manifest.body.version, proofToken: insertion.proofToken, programmingSourceProofToken: insertion.programmingSourceProofToken, scheduleItemId: insertion.scheduleItemId, itemType: insertion.itemType, programmingSource: insertion.programmingSource, eventType: "COMPLETED", occurredAt: new Date().toISOString(), positionSeconds: 60 };
    const invalidProof = await api("/api/player/proof-of-play", { method: "POST", cookie: playerCookie, body: { events: [{ ...proof, scheduleItemId: "f".repeat(64) }] } });
    assert.equal(invalidProof.status, 400);
    const genericScheduleId = "e".repeat(64);
    const genericBase = { playerId: player.id, manifestVersion: manifest.body.version, scheduleItemId: genericScheduleId, contentId: song.id };
    assert.equal((await api("/api/player/proof-of-play", { method: "POST", cookie: playerCookie, body: { events: [{ ...proof, eventId: randomUUID(), scheduleItemId: genericScheduleId, itemType: "MUSIC", trackId: song.id, programmingSource: "DEFAULT_AUTODJ", proofToken: createPlaybackProofToken(genericBase, secret), programmingSourceProofToken: createPlaybackProofToken({ ...genericBase, programmingSource: "DEFAULT_AUTODJ" }, secret) }] } })).status, 400);
    assert.equal((await api("/api/player/proof-of-play", { method: "POST", cookie: `ruvanas_player=${otherPlayerToken}`, body: { events: [proof] } })).status, 400);
    assert.equal((await api("/api/player/proof-of-play", { method: "POST", cookie: playerCookie, body: { events: [{ ...proof, itemType: "MUSIC", trackId: randomUUID() }] } })).status, 400);
    const failed = await api("/api/player/proof-of-play", { method: "POST", cookie: playerCookie, body: { events: [{ ...proof, eventId: randomUUID(), eventType: "FAILED", positionSeconds: 0 }] } });
    assert.equal(failed.status, 200, JSON.stringify(failed.body));
    assert.equal((await db.correctionsRequest.findUnique({ where: { id: requestId } })).status, "SCHEDULED");
    const confirmed = await api("/api/player/proof-of-play", { method: "POST", cookie: playerCookie, body: { events: [proof] } });
    assert.equal(confirmed.status, 200, JSON.stringify(confirmed.body));
    assert.equal((await db.correctionsRequest.findUnique({ where: { id: requestId } })).status, "PLAYED");
    const repeat = await api("/api/player/proof-of-play", { method: "POST", cookie: playerCookie, body: { events: [proof] } });
    assert.equal(repeat.status, 200); assert.equal(repeat.body.accepted, 0);
    assert.equal(await db.auditLog.count({ where: { organisationId: organisation.id, action: "CORRECTIONS_REQUEST_DELIVERY_CONFIRMED" } }), 1);
    const requestReport = await api(`/api/corrections/requests/${requestId}`, { cookie: ownerCookie });
    assert.ok(requestReport.body.request.delivery.evidence);

    const missedCreate = await api("/api/corrections/requests", { method: "POST", cookie: ownerCookie, body: { facilityId: location.id, type: "PROGRAMME", songTitle: "Undelivered request" } });
    assert.equal(missedCreate.status, 201);
    const missedPath = `/api/corrections/requests/${missedCreate.body.request.id}`;
    assert.equal((await api(missedPath, { method: "POST", cookie: ownerCookie, body: { action: "SCREEN" } })).status, 200);
    assert.equal((await api(missedPath, { method: "POST", cookie: ownerCookie, body: { action: "APPROVE", programmeId: programme.id } })).status, 200);
    const missedSchedule = await api(`${missedPath}/schedule`, { method: "POST", cookie: ownerCookie, body: { zoneId: zone.id, programmeId: programme.id, startsAt: new Date(Date.now() + 12 * 60_000).toISOString() } });
    assert.equal(missedSchedule.status, 200, JSON.stringify(missedSchedule.body));
    await db.playoutIntent.updateMany({ where: { correctionsRequestId: missedCreate.body.request.id }, data: { plannedStart: new Date(Date.now() - 180_000), expiresAt: new Date(Date.now() - 60_000) } });
    const missedReport = await api(missedPath, { cookie: ownerCookie });
    assert.equal(missedReport.body.request.status, "SCHEDULED");
    assert.equal(missedReport.body.request.delivery.needsAttention, true);
    assert.equal(missedReport.body.request.delivery.evidence, null);

    const rehabPath = `/api/corrections/rehabilitation/${rehab.id}/schedule`;
    const rehabStartsAt = new Date(Date.now() + 9 * 60_000).toISOString();
    await db.correctionsRehabContent.update({ where: { id: rehab.id }, data: { status: "DRAFT" } });
    assert.equal((await api(rehabPath, { method: "POST", cookie: ownerCookie, body: { facilityId: location.id, zoneId: zone.id, programmeId: programme.id, startsAt: rehabStartsAt } })).status, 409);
    await db.correctionsRehabContent.update({ where: { id: rehab.id }, data: { status: "APPROVED" } });
    assert.equal((await api(rehabPath, { method: "POST", cookie: ownerCookie, body: { facilityId: location.id, zoneId: otherFacility.zones[0].id, programmeId: programme.id, startsAt: rehabStartsAt } })).status, 409);
    const rehabScheduled = await api(rehabPath, { method: "POST", cookie: ownerCookie, body: { facilityId: location.id, zoneId: zone.id, programmeId: programme.id, startsAt: rehabStartsAt } });
    assert.equal(rehabScheduled.status, 200, JSON.stringify(rehabScheduled.body));
    assert.equal((await api(rehabPath, { method: "POST", cookie: ownerCookie, body: { facilityId: location.id, zoneId: zone.id, programmeId: programme.id, startsAt: rehabStartsAt } })).body.delivery.alreadyScheduled, true);
    const before = await api("/api/corrections/rehabilitation", { cookie: ownerCookie });
    assert.equal(before.body.content.find((item) => item.id === rehab.id).delivery.delivered, 0);
    await db.playoutIntent.updateMany({ where: { correctionsRequestId: requestId }, data: { expiresAt: new Date(Date.now() - 1000) } });
    await db.playoutIntent.updateMany({ where: { correctionsRehabContentId: rehab.id }, data: { plannedStart: new Date(Date.now() - 2000), expiresAt: new Date(Date.now() + 90_000) } });
    const rehabManifest = await api("/api/player/manifest", { cookie: playerCookie, instanceId });
    const rehabInsertion = rehabManifest.body.insertions.find((item) => item.programmingSource === "CORRECTIONS_REHABILITATION");
    assert.ok(rehabInsertion?.proofToken, JSON.stringify(rehabManifest.body.insertions));
    const rehabProof = { eventId: randomUUID(), manifestVersion: rehabManifest.body.version, proofToken: rehabInsertion.proofToken, programmingSourceProofToken: rehabInsertion.programmingSourceProofToken, scheduleItemId: rehabInsertion.scheduleItemId, itemType: rehabInsertion.itemType, programmingSource: rehabInsertion.programmingSource, eventType: "COMPLETED", occurredAt: new Date().toISOString(), positionSeconds: 45 };
    const rehabProofs = await Promise.all([rehabProof, { ...rehabProof, eventId: randomUUID() }].map((event) => api("/api/player/proof-of-play", { method: "POST", cookie: playerCookie, body: { events: [event] } })));
    assert.ok(rehabProofs.every((item) => item.status === 200), JSON.stringify(rehabProofs));
    assert.equal(rehabProofs.reduce((sum, item) => sum + item.body.accepted, 0), 1);
    const after = await api("/api/corrections/rehabilitation", { cookie: ownerCookie });
    const result = after.body.content.find((item) => item.id === rehab.id).delivery;
    assert.equal(result.delivered, 1);
    assert.equal(result.deliveredSeconds, 45);
    assert.equal(result.deliveryEvents[0].programmeId, programme.id);
    assert.equal(result.deliveryEvents[0].facilityId, location.id);
    assert.equal(result.deliveryEvents[0].channelId, channel.id);
  } finally {
    if (organisation) {
      await db.rightsUsageLedgerEvent.deleteMany({ where: { organisationId: organisation.id } });
      await db.proofOfPlayEvent.deleteMany({ where: { organisationId: organisation.id } });
      await db.playoutIntent.deleteMany({ where: { organisationId: organisation.id } });
      await db.correctionsRequestDecision.deleteMany({ where: { organisationId: organisation.id } });
      await db.correctionsRequest.deleteMany({ where: { organisationId: organisation.id } });
      await db.correctionsRehabProgrammeItem.deleteMany({ where: { programme: { organisationId: organisation.id } } });
      await db.correctionsRehabContent.deleteMany({ where: { organisationId: organisation.id } });
      await db.correctionsRehabCategory.deleteMany({ where: { organisationId: organisation.id } });
      await db.correctionsReview.deleteMany({ where: { submission: { organisationId: organisation.id } } });
      await db.correctionsSubmission.deleteMany({ where: { organisationId: organisation.id } });
      await db.correctionsProgramme.deleteMany({ where: { organisationId: organisation.id } });
      await db.audioRender.deleteMany({ where: { organisationId: organisation.id } });
      await db.audioProjectVersion.deleteMany({ where: { project: { organisationId: organisation.id } } });
      await db.audioProject.deleteMany({ where: { organisationId: organisation.id } });
      await db.promoVersion.deleteMany({ where: { promoAsset: { organisationId: organisation.id } } });
      await db.promoAsset.deleteMany({ where: { organisationId: organisation.id } });
      await db.track.deleteMany({ where: { mediaAsset: { organisationId: organisation.id } } });
      await db.mediaAsset.deleteMany({ where: { organisationId: organisation.id } });
      await db.playerListenerLease.deleteMany({ where: { organisationId: organisation.id } });
      await db.player.deleteMany({ where: { organisationId: organisation.id } });
      await db.channelAssignment.deleteMany({ where: { channel: { organisationId: organisation.id } } });
      await db.channel.deleteMany({ where: { organisationId: organisation.id } });
      await db.station.deleteMany({ where: { organisationId: organisation.id } });
      await db.organisation.delete({ where: { id: organisation.id } });
    }
    if (otherOrganisation) await db.organisation.delete({ where: { id: otherOrganisation.id } });
    for (const user of [owner, manager, viewer, contributor, outsider].filter(Boolean)) await db.user.delete({ where: { id: user.id } });
    if (plan) await db.plan.delete({ where: { id: plan.id } });
    await db.$disconnect();
  }
});
