-- HF.1: additive enum values. Keeping enum changes in their own migration
-- lets PostgreSQL commit them before later statements use the new values.
ALTER TYPE "PlanProductFamily" ADD VALUE IF NOT EXISTS 'HEALTH';
ALTER TYPE "PlanProductFamily" ADD VALUE IF NOT EXISTS 'FAITH';
ALTER TYPE "MusicRightsUse" ADD VALUE IF NOT EXISTS 'HEALTH_RADIO';
ALTER TYPE "MusicRightsUse" ADD VALUE IF NOT EXISTS 'FAITH_RADIO';
ALTER TYPE "PodcastProduct" ADD VALUE IF NOT EXISTS 'HEALTH_RADIO';
ALTER TYPE "PodcastProduct" ADD VALUE IF NOT EXISTS 'FAITH_RADIO';
ALTER TYPE "LiveStudioProduct" ADD VALUE IF NOT EXISTS 'HEALTH_RADIO';
ALTER TYPE "LiveStudioProduct" ADD VALUE IF NOT EXISTS 'FAITH_RADIO';
ALTER TYPE "AutoDjTargetType" ADD VALUE IF NOT EXISTS 'HEALTH_CHANNEL';
ALTER TYPE "AutoDjTargetType" ADD VALUE IF NOT EXISTS 'FAITH_CHANNEL';
ALTER TYPE "StudioProductDestination" ADD VALUE IF NOT EXISTS 'HEALTH_ANNOUNCEMENT';
ALTER TYPE "StudioProductDestination" ADD VALUE IF NOT EXISTS 'HEALTH_PODCAST';
ALTER TYPE "StudioProductDestination" ADD VALUE IF NOT EXISTS 'FAITH_SERMON';
ALTER TYPE "StudioProductDestination" ADD VALUE IF NOT EXISTS 'FAITH_ANNOUNCEMENT';
ALTER TYPE "StudioProductDestination" ADD VALUE IF NOT EXISTS 'FAITH_PODCAST';

CREATE TYPE "StationAudiencePolicy" AS ENUM ('INTERNAL', 'RESTRICTED', 'PUBLIC');
