-- Phase 3C: immutable campaign playout intent and polymorphic playback evidence.
ALTER TYPE "ProofOfPlayEventType" ADD VALUE IF NOT EXISTS 'INTERRUPTED';

CREATE TYPE "PlaybackItemType" AS ENUM ('MUSIC', 'PROMO');

CREATE TABLE "PlayoutIntent" (
    "id" TEXT NOT NULL,
    "scheduleItemId" TEXT NOT NULL,
    "organisationId" TEXT NOT NULL,
    "playerId" TEXT NOT NULL,
    "zoneId" TEXT NOT NULL,
    "channelId" TEXT,
    "campaignId" TEXT NOT NULL,
    "promoVersionId" TEXT NOT NULL,
    "mediaAssetId" TEXT NOT NULL,
    "publicationRevision" INTEGER NOT NULL,
    "sourceRevision" TEXT NOT NULL,
    "plannedStart" TIMESTAMP(3) NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PlayoutIntent_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "ProofOfPlayEvent"
  ADD COLUMN "scheduleItemId" TEXT,
  ADD COLUMN "itemType" "PlaybackItemType" NOT NULL DEFAULT 'MUSIC',
  ADD COLUMN "campaignId" TEXT,
  ADD COLUMN "promoVersionId" TEXT,
  ADD COLUMN "playoutIntentId" TEXT,
  ADD COLUMN "channelId" TEXT,
  ALTER COLUMN "trackId" DROP NOT NULL;

UPDATE "ProofOfPlayEvent"
SET "scheduleItemId" = 'legacy:' || "id"
WHERE "scheduleItemId" IS NULL;

ALTER TABLE "ProofOfPlayEvent" ALTER COLUMN "scheduleItemId" SET NOT NULL;

-- Client event IDs are UUIDs generated by players and are globally idempotent.
WITH duplicate_events AS (
  SELECT "id", ROW_NUMBER() OVER (PARTITION BY "clientEventId" ORDER BY "receivedAt", "id") AS duplicate_number
  FROM "ProofOfPlayEvent"
)
UPDATE "ProofOfPlayEvent" event
SET "clientEventId" = event."clientEventId" || ':legacy:' || event."id"
FROM duplicate_events duplicate
WHERE event."id" = duplicate."id" AND duplicate.duplicate_number > 1;

DROP INDEX IF EXISTS "ProofOfPlayEvent_playerId_clientEventId_key";

CREATE UNIQUE INDEX "PlayoutIntent_scheduleItemId_key" ON "PlayoutIntent"("scheduleItemId");
CREATE UNIQUE INDEX "PlayoutIntent_playerId_campaignId_publicationRevision_plannedStart_key"
  ON "PlayoutIntent"("playerId", "campaignId", "publicationRevision", "plannedStart");
CREATE INDEX "PlayoutIntent_organisationId_plannedStart_idx" ON "PlayoutIntent"("organisationId", "plannedStart");
CREATE INDEX "PlayoutIntent_playerId_plannedStart_idx" ON "PlayoutIntent"("playerId", "plannedStart");
CREATE INDEX "PlayoutIntent_zoneId_plannedStart_idx" ON "PlayoutIntent"("zoneId", "plannedStart");
CREATE INDEX "PlayoutIntent_channelId_plannedStart_idx" ON "PlayoutIntent"("channelId", "plannedStart");
CREATE INDEX "PlayoutIntent_campaignId_plannedStart_idx" ON "PlayoutIntent"("campaignId", "plannedStart");
CREATE INDEX "PlayoutIntent_promoVersionId_plannedStart_idx" ON "PlayoutIntent"("promoVersionId", "plannedStart");
CREATE INDEX "PlayoutIntent_expiresAt_idx" ON "PlayoutIntent"("expiresAt");

CREATE UNIQUE INDEX "ProofOfPlayEvent_clientEventId_key" ON "ProofOfPlayEvent"("clientEventId");
CREATE INDEX "ProofOfPlayEvent_scheduleItemId_idx" ON "ProofOfPlayEvent"("scheduleItemId");
CREATE INDEX "ProofOfPlayEvent_campaignId_occurredAt_idx" ON "ProofOfPlayEvent"("campaignId", "occurredAt");
CREATE INDEX "ProofOfPlayEvent_promoVersionId_occurredAt_idx" ON "ProofOfPlayEvent"("promoVersionId", "occurredAt");
CREATE INDEX "ProofOfPlayEvent_playoutIntentId_occurredAt_idx" ON "ProofOfPlayEvent"("playoutIntentId", "occurredAt");
CREATE INDEX "ProofOfPlayEvent_channelId_occurredAt_idx" ON "ProofOfPlayEvent"("channelId", "occurredAt");

ALTER TABLE "PlayoutIntent" ADD CONSTRAINT "PlayoutIntent_organisationId_fkey" FOREIGN KEY ("organisationId") REFERENCES "Organisation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PlayoutIntent" ADD CONSTRAINT "PlayoutIntent_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PlayoutIntent" ADD CONSTRAINT "PlayoutIntent_zoneId_fkey" FOREIGN KEY ("zoneId") REFERENCES "Zone"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PlayoutIntent" ADD CONSTRAINT "PlayoutIntent_channelId_fkey" FOREIGN KEY ("channelId") REFERENCES "Channel"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PlayoutIntent" ADD CONSTRAINT "PlayoutIntent_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PlayoutIntent" ADD CONSTRAINT "PlayoutIntent_promoVersionId_fkey" FOREIGN KEY ("promoVersionId") REFERENCES "PromoVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PlayoutIntent" ADD CONSTRAINT "PlayoutIntent_mediaAssetId_fkey" FOREIGN KEY ("mediaAssetId") REFERENCES "MediaAsset"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "ProofOfPlayEvent" ADD CONSTRAINT "ProofOfPlayEvent_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProofOfPlayEvent" ADD CONSTRAINT "ProofOfPlayEvent_promoVersionId_fkey" FOREIGN KEY ("promoVersionId") REFERENCES "PromoVersion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProofOfPlayEvent" ADD CONSTRAINT "ProofOfPlayEvent_playoutIntentId_fkey" FOREIGN KEY ("playoutIntentId") REFERENCES "PlayoutIntent"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProofOfPlayEvent" ADD CONSTRAINT "ProofOfPlayEvent_channelId_fkey" FOREIGN KEY ("channelId") REFERENCES "Channel"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "PlayoutIntent" ADD CONSTRAINT "PlayoutIntent_publication_revision_check"
  CHECK ("publicationRevision" > 0);
ALTER TABLE "PlayoutIntent" ADD CONSTRAINT "PlayoutIntent_expiry_check"
  CHECK ("expiresAt" > "plannedStart");
ALTER TABLE "ProofOfPlayEvent" ADD CONSTRAINT "ProofOfPlayEvent_item_shape_check" CHECK (
  ("itemType" = 'MUSIC' AND "trackId" IS NOT NULL AND "campaignId" IS NULL AND "promoVersionId" IS NULL AND "playoutIntentId" IS NULL)
  OR
  ("itemType" = 'PROMO' AND "trackId" IS NULL AND "campaignId" IS NOT NULL AND "promoVersionId" IS NOT NULL AND "playoutIntentId" IS NOT NULL)
);
