"use client";

import { useEffect, useState } from "react";
import styles from "./workspace.module.css";

const TABS = [
  ["overview", "Overview"], ["announcements", "Announcements"], ["events", "Events & live"], ["sponsors", "Sponsors"], ["branches", "Branches"]
];
const SURFACES = [["RADIO", "Radio"], ["PODCAST", "Podcast"], ["DISPLAY", "Digital display"], ["WEB_PLAYER", "Web player"], ["MOBILE_PLAYER", "Mobile player"]];

export default function OrganisationsWorkspace() {
  const [data, setData] = useState(null);
  const [tab, setTab] = useState("overview");
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  async function load() { const response = await fetch("/api/organisations/workspace", { cache: "no-store" }); const payload = await response.json(); if (response.ok) setData(payload); else setMessage(payload.error); }
  useEffect(() => { const query = new URLSearchParams(window.location.search); const requested = query.get("tab"); if (TABS.some(([key]) => key === requested)) setTab(requested); load(); }, []);
  async function submit(event, action) { event.preventDefault(); const formElement = event.currentTarget; setBusy(true); setMessage(""); const form = new FormData(formElement); const body = { action, ...Object.fromEntries(form.entries()) }; if (action === "CREATE_ANNOUNCEMENT") { body.surfaces = form.getAll("surfaces"); body.targetLocationIds = form.getAll("targetLocationIds"); body.targetStationIds = form.getAll("targetStationIds"); } for (const key of ["stationId", "channelId", "fallbackAutoDjPolicyId", "startsAt", "endsAt"]) if (!body[key]) delete body[key]; const response = await fetch("/api/organisations/workspace", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); setBusy(false); setMessage(response.ok ? "Saved successfully." : payload.error); if (response.ok) { formElement.reset(); await load(); } }
  async function act(action, key, value, extra = {}) { setBusy(true); const response = await fetch("/api/organisations/workspace", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, [key]: value, ...extra }) }); const payload = await response.json(); setBusy(false); setMessage(response.ok ? "Status updated." : payload.error); if (response.ok) await load(); }
  return <main className={styles.page} id="main-content"><header><p className={styles.eyebrow}>RUVANAS ORGANISATIONS</p><h1>Media operations, one area at a time</h1><p>Govern communications without storing membership, donor, HR, accounting, election or voter records.</p></header>
    <nav className={styles.tabs} aria-label="Organisations workspace">{TABS.map(([key, label]) => <button key={key} className={tab === key ? styles.active : ""} onClick={() => setTab(key)}>{label}</button>)}</nav>
    {message ? <p role="status" className={styles.message}>{message}</p> : null}
    {!data ? <p>Loading workspace…</p> : null}
    {data && tab === "overview" ? <><section className={styles.grid}><article><h2>Current plan</h2><strong>{data.entitlements.planCode}</strong><p>{data.entitlements.stationLimit} channels · Tier {data.entitlements.planTierNumber}</p></article><article><h2>Governed announcements</h2><strong>{data.announcements.length}</strong><p>Draft, approval and publication history retained.</p></article><article><h2>Event Mode</h2><strong>{data.events.length}</strong><p>Pre-event, live and post-event states with fallback.</p></article><article><h2>Network controls</h2><strong>{data.permissions.networkControls ? "Available" : "Tier 4+"}</strong><p>Branch delegation remains plan-gated.</p></article></section>{data.permissions.canManage ? <form className={styles.card} onSubmit={(event) => submit(event, "UPDATE_PROFILE")}><h2>Organisation media profile</h2><div className={styles.formRow}><label>Template<select name="template" defaultValue={data.profile?.template || "GENERAL"}><option value="GENERAL">General organisation</option><option value="NGO_CHARITY">NGO or charity</option><option value="SPORTS_CLUB">Sports club</option><option value="ASSOCIATION">Association</option><option value="COMMUNITY_CULTURAL">Community or cultural</option><option value="POLITICAL_CIVIC">Political or civic</option><option value="FEDERATION_NETWORK">Federation or network</option></select></label><label>Locale<input name="locale" defaultValue={data.profile?.locale || "en-MT"} /></label><label>Timezone<input name="timezone" defaultValue={data.profile?.timezone || "Europe/Malta"} /></label></div><label>Organisation disclosure<textarea name="disclosureText" defaultValue={data.profile?.disclosureText || ""} /></label><button disabled={busy}>Save profile</button></form> : null}</> : null}
    {data && tab === "announcements" ? <section className={styles.two}><form className={styles.card} onSubmit={(event) => submit(event, "CREATE_ANNOUNCEMENT")}><h2>New announcement</h2><label>Title<input name="title" required minLength="2" maxLength="180" /></label><label>Message<textarea name="body" required minLength="2" maxLength="8000" /></label><fieldset><legend>Publication surfaces</legend>{SURFACES.map(([value, label]) => <label className={styles.check} key={value}><input type="checkbox" name="surfaces" value={value} /> {label}</label>)}</fieldset><div className={styles.formRow}><label>Branches or venues<select name="targetLocationIds" multiple size="4">{data.locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select><small>Leave empty for the whole organisation.</small></label><label>Organisation channels<select name="targetStationIds" multiple size="4">{data.stations.map((station) => <option key={station.id} value={station.id}>{station.name}</option>)}</select><small>Leave empty for all organisation channels.</small></label></div><div className={styles.formRow}><label>Starts (optional)<input name="startsAt" type="datetime-local" /></label><label>Ends (optional)<input name="endsAt" type="datetime-local" /></label></div><button disabled={busy}>Save draft</button></form><div className={styles.card}><h2>Announcement queue</h2>{data.announcements.map((item) => <article className={styles.item} key={item.id}><strong>{item.title}</strong><small>{item.status} · {item.surfaces.join(", ")}</small>{item.status === "DRAFT" && data.permissions.canManage ? <button onClick={() => act("APPROVE_ANNOUNCEMENT", "announcementId", item.id)}>Approve</button> : null}{item.status === "APPROVED" && data.permissions.canManage ? <button onClick={() => act("PUBLISH_ANNOUNCEMENT", "announcementId", item.id)}>Publish</button> : null}{!["ARCHIVED"].includes(item.status) && data.permissions.canManage ? <button onClick={() => act("ARCHIVE_ANNOUNCEMENT", "announcementId", item.id)}>Archive</button> : null}</article>)}</div></section> : null}
    {data && tab === "events" ? <section className={styles.two}><form className={styles.card} onSubmit={(event) => submit(event, "CREATE_EVENT")}><h2>Prepare Event Mode</h2><label>Event title<input name="title" required /></label><label>Starts<input name="startsAt" type="datetime-local" required /></label><label>Ends<input name="endsAt" type="datetime-local" required /></label><label>Timezone<input name="timezone" defaultValue={data.profile?.timezone || "Europe/Malta"} required /></label><label>Channel<select name="channelId" defaultValue=""><option value="">Choose later</option>{data.stations.flatMap((station) => station.channels.map((channel) => <option key={channel.id} value={channel.id}>{station.name} / {channel.name}</option>))}</select></label><label>AutoDJ fallback<select name="fallbackAutoDjPolicyId" defaultValue=""><option value="">Choose later</option>{data.autoDjPolicies.map((policy) => <option key={policy.id} value={policy.id}>{policy.name}</option>)}</select></label><button disabled={busy}>Create event draft</button></form><div className={styles.card}><h2>Event lifecycle</h2>{data.events.map((item) => <article className={styles.item} key={item.id}><strong>{item.title}</strong><small>{item.status}</small>{data.permissions.canManage && item.status === "DRAFT" ? <button onClick={() => act("TRANSITION_EVENT", "eventId", item.id, { status: "READY" })}>Mark ready</button> : null}{data.permissions.canManage && item.status === "READY" ? <button onClick={() => act("TRANSITION_EVENT", "eventId", item.id, { status: "LIVE" })}>Go live</button> : null}{data.permissions.canManage && item.status === "LIVE" ? <button onClick={() => act("TRANSITION_EVENT", "eventId", item.id, { status: "ENDED" })}>End event</button> : null}</article>)}</div></section> : null}
    {data && tab === "sponsors" ? <section className={styles.two}><form className={styles.card} onSubmit={(event) => submit(event, "CREATE_SPONSOR")}><h2>New sponsor profile</h2><label>Display name<input name="name" required /></label><label>Legal name<input name="legalName" /></label><label>Disclosure wording<textarea name="disclosureText" /></label><button disabled={busy}>Save sponsor</button></form><div className={styles.card}><h2>Sponsor profiles</h2><p>Campaign delivery evidence never claims impressions.</p>{data.sponsors.map((item) => <article className={styles.item} key={item.id}><strong>{item.name}</strong><small>{item.status}</small></article>)}</div></section> : null}
    {data && tab === "branches" ? <section className={styles.two}><div className={styles.card}><h2>Branches, chapters and venues</h2><p>{data.permissions.networkControls ? "Assign location-scoped operational permissions without exposing another branch." : "Upgrade to Organisations Network or Enterprise for branch delegation."}</p><a href="/dashboard/locations">Manage locations and zones →</a>{data.branchAssignments.map((item) => <article className={styles.item} key={item.id}><strong>{item.location.name}</strong><small>{item.organisationMember.user.name || item.organisationMember.user.email} · {item.permission}</small></article>)}</div>{data.permissions.networkControls ? <form className={styles.card} onSubmit={(event) => submit(event, "ASSIGN_BRANCH")}><h2>Delegate a branch</h2><label>Team member<select name="organisationMemberId" required><option value="">Choose member</option>{data.members.map((member) => <option key={member.id} value={member.id}>{member.user.name || member.user.email}</option>)}</select></label><label>Branch or venue<select name="locationId" required><option value="">Choose location</option>{data.locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label>Scope<select name="permission"><option value="VIEWER">View</option><option value="CONTENT">Content</option><option value="DISPLAY">Displays</option><option value="MANAGER">Branch manager</option></select></label><button disabled={busy}>Save delegation</button></form> : null}</section> : null}
  </main>;
}
