-- ORG.1: commit additive enum values before later migrations use them.
ALTER TYPE "PlanProductFamily" ADD VALUE IF NOT EXISTS 'ORGANISATIONS';
ALTER TYPE "MusicRightsUse" ADD VALUE IF NOT EXISTS 'ORGANISATIONS_RADIO';
ALTER TYPE "PodcastProduct" ADD VALUE IF NOT EXISTS 'ORGANISATIONS_RADIO';
ALTER TYPE "LiveStudioProduct" ADD VALUE IF NOT EXISTS 'ORGANISATIONS_RADIO';
ALTER TYPE "AutoDjTargetType" ADD VALUE IF NOT EXISTS 'ORGANISATIONS_CHANNEL';
ALTER TYPE "StudioProductDestination" ADD VALUE IF NOT EXISTS 'ORGANISATIONS_ANNOUNCEMENT';
ALTER TYPE "StudioProductDestination" ADD VALUE IF NOT EXISTS 'ORGANISATIONS_PODCAST';
ALTER TYPE "StudioProductDestination" ADD VALUE IF NOT EXISTS 'ORGANISATIONS_EVENT';

CREATE TYPE "OrganisationMediaTemplate" AS ENUM ('NGO_CHARITY', 'SPORTS_CLUB', 'ASSOCIATION', 'COMMUNITY_CULTURAL', 'POLITICAL_CIVIC', 'FEDERATION_NETWORK', 'GENERAL');
CREATE TYPE "OrganisationAnnouncementStatus" AS ENUM ('DRAFT', 'APPROVED', 'PUBLISHED', 'ARCHIVED');
CREATE TYPE "OrganisationAnnouncementSurface" AS ENUM ('RADIO', 'PODCAST', 'DISPLAY', 'WEB_PLAYER', 'MOBILE_PLAYER');
CREATE TYPE "OrganisationEventStatus" AS ENUM ('DRAFT', 'READY', 'LIVE', 'ENDED', 'CANCELLED');
CREATE TYPE "OrganisationSponsorStatus" AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');
CREATE TYPE "OrganisationBranchPermission" AS ENUM ('MANAGER', 'CONTENT', 'DISPLAY', 'VIEWER');
