ALTER TYPE "CampaignTargetType" ADD VALUE IF NOT EXISTS 'STATION';
ALTER TYPE "CampaignTargetType" ADD VALUE IF NOT EXISTS 'CHANNEL';
ALTER TYPE "RetailMediaInventoryTargetType" ADD VALUE IF NOT EXISTS 'STATION';
ALTER TYPE "RetailMediaInventoryTargetType" ADD VALUE IF NOT EXISTS 'CHANNEL';
